apiVersion: v1
kind: ConfigMap
metadata:
  name: mlops-config
  namespace: mlops
data:
  MLFLOW_TRACKING_URI: "http://mlflow-server.mlops.svc.cluster.local:5000"
  MODEL_NAME: "ChurnModel"
  MODEL_STAGE: "Production"
  MLFLOW_S3_ENDPOINT_URL: "http://minio.mlops.svc.cluster.local:9000"
  PREDICTIONS_STORE: "/app/data/predictions.csv"
  DRIFT_THRESHOLD: "0.3"
