FROM apache/airflow:2.8.1-python3.10

USER root
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

USER airflow

COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir \
    mlflow==2.12.1 \
    scikit-learn==1.4.2 \
    pandas==2.2.1 \
    numpy==1.26.4 \
    evidently==0.4.22 \
    optuna==3.6.1 \
    boto3==1.34.84 \
    psycopg2-binary==2.9.9

COPY src/ /opt/airflow/src/
